package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA



/**
 * Customstyle generated by hbm2java
 */
public class Customstyle  implements java.io.Serializable {


     private int styleid;
     private Product product;
     private String foldername;

    public Customstyle() {
    }

    public Customstyle(int styleid, Product product, String foldername) {
       this.styleid = styleid;
       this.product = product;
       this.foldername = foldername;
    }
   
    public int getStyleid() {
        return this.styleid;
    }
    
    public void setStyleid(int styleid) {
        this.styleid = styleid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getFoldername() {
        return this.foldername;
    }
    
    public void setFoldername(String foldername) {
        this.foldername = foldername;
    }




}


