package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DbVersion generated by hbm2java
 */
public class DbVersion  implements java.io.Serializable {


     private DbVersionId id;
     private Date ts;

    public DbVersion() {
    }

    public DbVersion(DbVersionId id, Date ts) {
       this.id = id;
       this.ts = ts;
    }
   
    public DbVersionId getId() {
        return this.id;
    }
    
    public void setId(DbVersionId id) {
        this.id = id;
    }
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


