package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Menuitem generated by hbm2java
 */
public class Menuitem  extends BaseEntity implements java.io.Serializable {


     private int menuitemid;
     private String menuitemname;
     private Set product2menuitems = new HashSet(0);
     private Set submenuitems = new HashSet(0);
     private Menuitem menuitem;
     private String action;
     private String cls;

    public Menuitem() {
    }

	
    public Menuitem(int menuitemid, String menuitemname) {
        this.menuitemid = menuitemid;
        this.menuitemname = menuitemname;
    }
    public Menuitem(int menuitemid, String menuitemname, Set product2menuitems) {
       this.menuitemid = menuitemid;
       this.menuitemname = menuitemname;
       this.product2menuitems = product2menuitems;
    }
   
    public int getMenuitemid() {
        return this.menuitemid;
    }
    
    public void setMenuitemid(int menuitemid) {
        this.menuitemid = menuitemid;
    }
    public String getMenuitemname() {
        return this.menuitemname;
    }
    
    public void setMenuitemname(String menuitemname) {
        this.menuitemname = menuitemname;
    }
    public Set getProduct2menuitems() {
        return this.product2menuitems;
    }
    
    public void setProduct2menuitems(Set product2menuitems) {
        this.product2menuitems = product2menuitems;
    }

    public Menuitem getMenuitem() {
        return menuitem;
    }

    public void setMenuitem(Menuitem menuitem) {
        this.menuitem = menuitem;
    }

    public Set getSubmenuitems() {
        return submenuitems;
    }

    public void setSubmenuitems(Set submenuitems) {
        this.submenuitems = submenuitems;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getCls() {
        return cls;
    }

    public void setCls(String cls) {
        this.cls = cls;
    }
}


