package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA



/**
 * Product2menuitem generated by hbm2java
 */
public class Product2menuitem  implements java.io.Serializable {


     private Product2menuitemId id;
     private Product product;
     private Menuitem menuitem;
     private boolean isactive;

    public Product2menuitem() {
    }

    public Product2menuitem(Product2menuitemId id, Product product, Menuitem menuitem, boolean isactive) {
       this.id = id;
       this.product = product;
       this.menuitem = menuitem;
       this.isactive = isactive;
    }
   
    public Product2menuitemId getId() {
        return this.id;
    }
    
    public void setId(Product2menuitemId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Menuitem getMenuitem() {
        return this.menuitem;
    }
    
    public void setMenuitem(Menuitem menuitem) {
        this.menuitem = menuitem;
    }
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }




}


