package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA



/**
 * Product2themeId generated by hbm2java
 */
public class Product2themeId  implements java.io.Serializable {


     private int productid;
     private int themeid;

    public Product2themeId() {
    }

    public Product2themeId(int productid, int themeid) {
       this.productid = productid;
       this.themeid = themeid;
    }
   
    public int getProductid() {
        return this.productid;
    }
    
    public void setProductid(int productid) {
        this.productid = productid;
    }
    public int getThemeid() {
        return this.themeid;
    }
    
    public void setThemeid(int themeid) {
        this.themeid = themeid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Product2themeId) ) return false;
		 Product2themeId castOther = ( Product2themeId ) other; 
         
		 return (this.getProductid()==castOther.getProductid())
 && (this.getThemeid()==castOther.getThemeid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductid();
         result = 37 * result + this.getThemeid();
         return result;
   }   


}


