package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA



/**
 * Product2menuitemId generated by hbm2java
 */
public class Product2menuitemId  implements java.io.Serializable {


     private int productid;
     private int menuitemid;

    public Product2menuitemId() {
    }

    public Product2menuitemId(int productid, int menuitemid) {
       this.productid = productid;
       this.menuitemid = menuitemid;
    }
   
    public int getProductid() {
        return this.productid;
    }
    
    public void setProductid(int productid) {
        this.productid = productid;
    }
    public int getMenuitemid() {
        return this.menuitemid;
    }
    
    public void setMenuitemid(int menuitemid) {
        this.menuitemid = menuitemid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Product2menuitemId) ) return false;
		 Product2menuitemId castOther = ( Product2menuitemId ) other; 
         
		 return (this.getProductid()==castOther.getProductid())
 && (this.getMenuitemid()==castOther.getMenuitemid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductid();
         result = 37 * result + this.getMenuitemid();
         return result;
   }   


}


