package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productid;
     private String connstring;
     private String url;
     private boolean isproduction;
     private String dbusername;
     private String dbpassword;
     private boolean isactive;
     private int gipsprodid;
     private String stylesfolder;
     private Set product2menuitems = new HashSet(0);
     private Set product2themes = new HashSet(0);
     private Set customstyles = new HashSet(0);

    public Product() {
    }

	
    public Product(String connstring, String url, boolean isproduction, String dbusername, String dbpassword, boolean isactive, int gipsprodid, String stylesfolder) {
        this.connstring = connstring;
        this.url = url;
        this.isproduction = isproduction;
        this.dbusername = dbusername;
        this.dbpassword = dbpassword;
        this.isactive = isactive;
        this.gipsprodid = gipsprodid;
        this.stylesfolder = stylesfolder;
    }
    public Product(String connstring, String url, boolean isproduction, String dbusername, String dbpassword, boolean isactive, int gipsprodid, String stylesfolder, Set product2menuitems, Set product2themes, Set customstyles) {
       this.connstring = connstring;
       this.url = url;
       this.isproduction = isproduction;
       this.dbusername = dbusername;
       this.dbpassword = dbpassword;
       this.isactive = isactive;
       this.gipsprodid = gipsprodid;
       this.stylesfolder = stylesfolder;
       this.product2menuitems = product2menuitems;
       this.product2themes = product2themes;
       this.customstyles = customstyles;
    }
   
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
    public String getConnstring() {
        return this.connstring;
    }
    
    public void setConnstring(String connstring) {
        this.connstring = connstring;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public boolean isIsproduction() {
        return this.isproduction;
    }
    
    public void setIsproduction(boolean isproduction) {
        this.isproduction = isproduction;
    }
    public String getDbusername() {
        return this.dbusername;
    }
    
    public void setDbusername(String dbusername) {
        this.dbusername = dbusername;
    }
    public String getDbpassword() {
        return this.dbpassword;
    }
    
    public void setDbpassword(String dbpassword) {
        this.dbpassword = dbpassword;
    }
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }
    public int getGipsprodid() {
        return this.gipsprodid;
    }
    
    public void setGipsprodid(int gipsprodid) {
        this.gipsprodid = gipsprodid;
    }
    public String getStylesfolder() {
        return this.stylesfolder;
    }
    
    public void setStylesfolder(String stylesfolder) {
        this.stylesfolder = stylesfolder;
    }
    public Set getProduct2menuitems() {
        return this.product2menuitems;
    }
    
    public void setProduct2menuitems(Set product2menuitems) {
        this.product2menuitems = product2menuitems;
    }
    public Set getProduct2themes() {
        return this.product2themes;
    }
    
    public void setProduct2themes(Set product2themes) {
        this.product2themes = product2themes;
    }
    public Set getCustomstyles() {
        return this.customstyles;
    }
    
    public void setCustomstyles(Set customstyles) {
        this.customstyles = customstyles;
    }




}


