package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA



/**
 * Product2theme generated by hbm2java
 */
public class Product2theme  implements java.io.Serializable {


     private Product2themeId id;
     private Theme theme;
     private Product product;
     private boolean isactive;

    public Product2theme() {
    }

    public Product2theme(Product2themeId id, Theme theme, Product product, boolean isactive) {
       this.id = id;
       this.theme = theme;
       this.product = product;
       this.isactive = isactive;
    }
   
    public Product2themeId getId() {
        return this.id;
    }
    
    public void setId(Product2themeId id) {
        this.id = id;
    }
    public Theme getTheme() {
        return this.theme;
    }
    
    public void setTheme(Theme theme) {
        this.theme = theme;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public boolean isIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(boolean isactive) {
        this.isactive = isactive;
    }




}


