package com.java.web.core.domain.access;
// Generated Oct 4, 2011 11:16:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Theme generated by hbm2java
 */
public class Theme  implements java.io.Serializable {


     private int themeid;
     private String themename;
     private Set product2themes = new HashSet(0);

    public Theme() {
    }

	
    public Theme(int themeid, String themename) {
        this.themeid = themeid;
        this.themename = themename;
    }
    public Theme(int themeid, String themename, Set product2themes) {
       this.themeid = themeid;
       this.themename = themename;
       this.product2themes = product2themes;
    }
   
    public int getThemeid() {
        return this.themeid;
    }
    
    public void setThemeid(int themeid) {
        this.themeid = themeid;
    }
    public String getThemename() {
        return this.themename;
    }
    
    public void setThemename(String themename) {
        this.themename = themename;
    }
    public Set getProduct2themes() {
        return this.product2themes;
    }
    
    public void setProduct2themes(Set product2themes) {
        this.product2themes = product2themes;
    }




}


